#ifndef ZEPHYR_INCLUDE_DRIVERS_FLASH_RA_FLASH_API_EXTENSIONS_H_
#define ZEPHYR_INCLUDE_DRIVERS_FLASH_RA_FLASH_API_EXTENSIONS_H_

#include <zephyr/drivers/flash.h>

enum ra_flash_ex_ops {
	FLASH_RA_EX_OP_BANK_SWAP = FLASH_EX_OP_VENDOR_BASE,
	QSPI_FLASH_EX_OP_EXIT_QPI,
};

#endif
